import { Inter, Electrolize } from 'next/font/google';
import './globals.css';
import Navbar from '@/Components/Nav/Navbar';
import Footer from '@/Components/Footer/Footer';

const electrolize = Electrolize({ subsets: ['latin'], weight: '400' });
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`text-[#fff] bg-header ${electrolize.className}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
